"""Configuration for file organization infrastructure."""

from .file_organization_config import (
    DEFAULT_INPUT_FOLDER,
    DEFAULT_DONE_FOLDER,
    PROJECT_ROOT,
    ARCHIVE_TIMESTAMP_FORMAT,
    FOLDER_CREATION_ERROR_TEMPLATE,
    FILE_COPY_ERROR_TEMPLATE,
    FILE_ACCESS_ERROR_TEMPLATE,
    INPUT_FOLDER_NAME,
    DONE_FOLDER_NAME,
)

__all__ = [
    "DEFAULT_INPUT_FOLDER",
    "DEFAULT_DONE_FOLDER",
    "PROJECT_ROOT",
    "ARCHIVE_TIMESTAMP_FORMAT",
    "FOLDER_CREATION_ERROR_TEMPLATE",
    "FILE_COPY_ERROR_TEMPLATE",
    "FILE_ACCESS_ERROR_TEMPLATE",
    "INPUT_FOLDER_NAME",
    "DONE_FOLDER_NAME",
]
